---
name: ResinAPI
version: 1.0.0
main: pixelwhiz\resinapi\ResinAPI
api: 5.0.0
author: pixelwhiz
src-namespace-prefix: pixelwhiz\resinapi

permissions:
  resinapi.commands:
    description: Allows executing resin commands.
    default: true
  resinapi.command.check:
    description: Allows checking the status of a resin.
    default: true
  resinapi.command.help:
    description: Allows executing the give command in resin.
    default: op
  resinapi.command.give:
    description: Allows giving a resin to another user.
    default: op
...
